#if defined(GCOM_TIMER)
GCOM_TIMER_TIME(THIS_TIMER)=GCOM_TIMER_TIME(THIS_TIMER)+          &
                            GCOM_TIMEDIFF(start_timestamp)
GCOM_TIMER_COUNT(THIS_TIMER)=GCOM_TIMER_COUNT(THIS_TIMER)+        &
  THIS_COUNT
GCOM_TIMER_DATA(THIS_TIMER)=GCOM_TIMER_DATA(THIS_TIMER)+          &
  THIS_LENGTH
#endif
