*IDENT RENAME
*/ modified version of Julia Tindall's rename_output.f mod to 
*/ cope with long filenames in paleoruns. As Absolute Long 
*/ format, but uses the year in an (i9.9) format in the 
*/ filename, with a + or - appended for past/future runs. The 
*/ middle character is changed from @ to # to indicate the new 
*/ format. Needs to be used with modified qx execs for full
*/ continuation run capabilities.
*/ - robin smith + jonathan gregory, 2007
*DECLARE DUMPCTL1
*D DUMPCTL1.80
      CHARACTER*21 DUMPNAME
*DECLARE MEANCTL1
*D MEANCTL1.85
*/ change size of files
      CHARACTER*21 PSNAME_READ,PSNAME_WRITE,PSNAME_DELETE
*D GKR1F404.356
 890      FORMAT('%%% ',A21,' DELETE')                                     
*DECLARE U_MODEL1
*D U_MODEL1.68
      CHARACTER*21 PPNAME       ! Work - Dummy PP filename   
*DECLARE INITIAL1
*D INITIAL1.93
*/ change size of file
      CHARACTER*21 PPNAME       ! Dummy PP file name returned by PPCTL  
*DECLARE MEANDIA2
*D MEANDIA2.105
*/ change size of file
      CHARACTER*21
*D MEANDIA2.507,MEANDIA2.511
 410  FORMAT("%%% ",A21," ARCHIVE PPCHART")
 420  FORMAT("%%% ",A21," ARCHIVE PPNOCHART")
 430  FORMAT("%%% ",A21," PLOTONLY PPCHART")
 440  FORMAT("%%% ",A21," DELETE")
 450  FORMAT("%%% ",A21," HPSEND")                                         
*DECLARE PPCTL2
*D PPCTL2.46
*/ change size of file
      CHARACTER*21 PPNAME       ! OUT - PP filename generated by GET_NAME 
*D PPCTL2.74
      CHARACTER*21 OLDPPFILE        ! Previous PPfile on given unit
*D PPCTL2.154,PPCTL2.155
      STRING(18:38)=PPNAME                       
      STRING(39:80)='                                       '
*D PPCTL2.281 
      OLDPPFILE=STRING(IPOS+1:IPOS+21)
*D PPCTL2.330,PPCTL2.335 
 100  FORMAT('%%% ',A21,' ARCHIVE PPCHART')
 110  FORMAT('%%% ',A21,' ARCHIVE PPNOCHART')
 120  FORMAT('%%% ',A21,' PLOTONLY PPCHART')
 130  FORMAT('%%% ',A21,' ARCHIVE BNDY')
 140  FORMAT('%%% ',A21,' HPSEND')
 150  FORMAT('%%% ',A21,' DELETE')
*D PPCTL2.372,PPCTL2.373
      STRING(18:38)=PPNAME        
      STRING(39:80)='                                       '   
*D PPCTL2.482,PPCTL2.483
      STRING(18:38)=PPNAME                 
      STRING(39:80)='                                       '      
*DECLARE GET_NAM2
*I GET_NAM2.71
      INTEGER absyear
*I GET_NAM2.86
      CHARACTER*1 PorM          ! Character plus/minus identifier
*D GET_NAM2.53
*/ change size of filename
      CHARACTER*21  FILENAME    ! OUT - Generated file name
*I GET_NAM2.178
      ELSE IF (TIME_CONVENTION.EQ.'Absolute_verylong') THEN
          SEPARATOR='#'
          STYLE='B'
*I GET_NAM2.377
      ELSE IF (TIME_CONVENTION.EQ.'Absolute_verylong') THEN
            absyear=abs(YYYY)
            write(FILENAME(10:18),'(i9.9)')absyear
            
            FILENAME(19:19)=M                                  
            FILENAME(20:20)=D   
            PorM                = '+'
            IF (YYYY.LT.0) PorM = '-'
            FILENAME(21:21)=PorM
*I GET_NAM2.437    
      ELSE IF (TIME_CONVENTION.EQ.'Absolute_verylong') THEN
            absyear=abs(YYYY)
            write(FILENAME(10:18),'(i9.9)')absyear

            FILENAME(19:19)=M                                  
            FILENAME(20:20)=D   
            PorM                   = '+'
            IF (YYYY.LT.0) PorM    = '-'
            FILENAME(21:21)=PorM

            IF (MEANLEV.eq.0) THEN                                     
              FILENAME(19:20) = MONTH_2CHAR(MM)                
            ELSE ! means date routine called is at beginning of next     
C                   period                                               
             MON=MM-1                                                   
             IF (MON.EQ.0) THEN                                    
               MON = 12                                            
             ENDIF                                                 
             IF (FILETYPE_2.eq.'m') THEN                           
               FILENAME(19:20) = MONTH_2CHAR(MON)                  
             ELSE                                                  
               FILENAME(19:20) = SEASON_2CHAR(MON)                 
             ENDIF                                                 
            ENDIF                                                  
*DECLARE SEC2TIM1
*I SEC2TIM1.81 
            IF (I_DAY.GE.0) THEN
*I SEC2TIM1.85 
            ELSE
               I_YEAR=((I_DAY+1)/360)-1
               I_DAY=I_DAY - (I_YEAR * 360) 
               I_MONTH = MOD(I_DAY/30,12)+1
               I_DAY   = MOD(I_DAY,30)+1
               I_DAY_NUMBER = I_DAY+30*(I_MONTH-1)
            ENDIF
*DECLARE STWORK1A
*/ change field length for long run
*D STWORK1A.266
            CHARACTER*21                          
*D STWORK1A.1143
            PPNAME=STRING(JJ+1:JJ+21)  
*DECLARE CHISTG
*D CHISTG.20
      CHARACTER*21 END_DUMPim(N_INTERNAL_MODEL_MAX)!most recent dumpname
*D GGH3F400.1 
      CHARACTER*21 SAFEDMPim(N_INTERNAL_MODEL_MAX)
*D GGH3F400.3 
      CHARACTER*21 NEWSAFEim(N_INTERNAL_MODEL_MAX)
*D GKR1F404.245
      CHARACTER*21 LASTATMim(N_INTERNAL_MODEL_MAX) ! Keep name of last
*D GKR1F404.248 
      CHARACTER*21 CURRATMim(N_INTERNAL_MODEL_MAX) ! Keep name of
*D GKR1F404.251
      CHARACTER*21 LASTDMPim(N_INTERNAL_MODEL_MAX) ! Keep name of last
*DECLARE CHISTO
*D CHISTO.20,CHISTO.21
      CHARACTER*21 RUN_COMPCODE        ! Run completion code
      CHARACTER*21 RUN_LAST_MEAN       ! Last mean dump created by run
*DECLARE INITCHS1
*D GRB1F305.97,GLW4F403.6
      RUN_COMPCODE='                     '
      RUN_LAST_MEAN='                     '
*D GRB1F305.120
*D GLW4F403.18,GKR1F404.259
      END_DUMPim(i)='                     '
      SAFEDMPim(i)='                     '
      NEWSAFEim(i)='                     '
      LASTATMim(i)='                     '
      CURRATMim(i)='                     '
      LASTDMPim(i)='                     '
c
*DECLARE DUMPCTL1
*D GKR1F404.242
 620  FORMAT('%%% ',A21,' ARCHIVE DUMP')
*D DUMPCTL1.372
 610    FORMAT('%%% ',A21,' DELETE')
*D DUMPCTL1.270
      ARESTART(18:38)=DUMPNAME
*D GDR3F305.27
      AOMEAN(18:38) = DUMPNAME
*D DUMPCTL1.320
      ORESTART(18:38)=DUMPNAME
*D WRB1F401.141
      WRESTART(18:38)=DUMPNAME
c
*DECLARE PRINTHS1
*D WRB1F401.704,WRB1F401.705
     *'Last Restart dump(s) written      : ',A21,3(4X,A21)/
     *'Current Restart dump(s) name      : ',A21,3(4X,A21)/
