#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  addcompileopts
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: ?????????????????????????
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: mkobjxref
#L
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables: none
#L
#L   End of header -----------------------------------------------------

addcompileopts()
{
  defcomb=$1
  opt=$2
  mergec=""

  if [[ "$opt" = *"<"[yY]">"* ]] && [[ "$opt" = [nda]* ]]
  then
    for defc in "$defcomb"
    do
      mergec=$defc"_"${opt%\<*\>}
      echo -e $mergec
    done
  # catch error clause 1
  elif [[ "$opt" != *"<"[nN]">"* ]] && [[ "$opt" = [nda]* ]]
  then
    for defc in "$defcomb"
    do
      # the compile option is other than yes or no default is to
      # build it
      mergec=$defc"_"${opt%\<*\>}
      echo -e $mergec
    done
  # catch error clause 2
  else
    # the compile option is other than n(ormal), d(ebug) or
    # a(pprentice) default is not to build anything
    :
  fi
}
