#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  checkhdefs
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: ?????????????????????????
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: mkobjxref
#L
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables: none
#L
#L   End of header -----------------------------------------------------

checkhdefs()
{
  # loop over each hard def and take appropriate action either ammending
  # the mccomb line or replacing removing the build lines
  for hdef in `echo -e $hdefstring`
  do
    if [[ "$mccomb" = *"$hdef<"[yY]":"[nN]">"* ]]
    then
      # if hdef is declared as hard and is both on and off on a
      # given platform then create a new (temporary) mccomb with
      # hdef set as being on
      holdstr=""
      for mcomb in `echo -e $mccomb`
      do
        if [[ "$mcomb" = "$hdef"* ]]
        then
          holdstr=$holdstr$hdef"<Y>"" "
        else
          holdstr=$holdstr$mcomb" "
        fi
      done
      mccomb=$holdstr
    elif [[ "$mccomb" = *"$hdef<"[nN]">"* ]]
    then
      # if hdef is declared as hard and should not be set on a given
      # platform then break from the loop and remove build lines for
      # this section from the xref
      SKIPSECTION=true
      break
    fi
  done
}
