#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  findstr
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: Looks for a specific string in a list of strings.
#LL
#LL  Inputs : $1 = the string to search
#LL           $2 = a list of strings, with the whole thing
#LL                surrounded by "".
#LL
#LL  Outputs : Y, if the string is found
#LL            N, if the string isn't found
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: mkobjxref, mkexecxref
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables: none
#L
#L   End of header -----------------------------------------------------

findstr()
{
  fstring=$1
  shift
  instring=`echo -e $* | tr "," " "`

  for string in $instring
  do
    echo -e $string| $UM_GREP -x $fstring  > /dev/null
    CC=$?
    if [ $CC -eq 0 ]
    then
      echo -e "Y"
      exit
    fi
  done
  echo -e "N"
}
