#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  fnusage
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: Displays a help page for script qsconf
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: qsconf
#L
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables: none
#L
#L   End of header -----------------------------------------------------

fnusage()
{
  cat <<EOF >&1

UKMO Unified Model global configuration script for versions of
the UM at or later than 4.2. Bug reports may be sent by email
to abrady@meto.gov.uk.

USAGE: qsconf [-sections -execs] [-optargs] [execs,sects...]
  -quiet1                -- Message level set to 1
  -execs                 -- Build only small executables
  -sections              -- Build only UM sections
  -cemod   <modfiles,..> -- C-code mods files for small executables
  -femod   <modfiles,..> -- Fortran mods files for small executables
  -csmod   <modfiles,..> -- C-code mods files for sections
  -fsmod   <modfiles,..> -- Fortran mods files for sections
  -ignore                -- Ignore missing mod files.
  -objx    <objxref>     -- Use user objxref file [$OBJXREF]
  -execx   <execxref>    -- Use user execxref file [$EXECXREF]
  -compvar <file>        -- Use user compile_vars file [$COMPVARS]
  -outdir  <dir>         -- Directory to put output in [$OUTDIR]
  -umdir   <dir>         -- UM root directory  [$UMDIR]
  -vn      <version>     -- UM version to use [$VN]
  -cgopts  <regexp>      -- Build only sects with COMP_GEN_OPTS
                            matching regexp. Ignored for execs build.
  -defcom  <defs>        -- Build sects with given DEF combinations.
                            Ignored for execs build.
  -help                  -- This help

If no executable or section names are given as arguments then all of
either sections and/or executables will be configured. If you
specify -sections then only sections (with filter applied) will be
configured. If you specify -execs, then only small executables (with
filter applied) will be configured.

Examples.

eg. To configure the entire model under UMDIR
        \$ qsconf -sections -execs

eg. To configure section c95_2a under UMDIR
        \$ qsconf -sections c95_2a

eg. To configure qxrecon_dump in local directory test_qx
        \$ qsconf -outdir test_qx -execs qxrecon_dump

Notes.

1. Modfile pathnames must be comma separated.

2. Filter arguments should come at the end of the argument list and
may be space or comma seperated.  Command args must not follow the
filter arguments.

Copyright UKMO 1996.

EOF
}
