#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  gen_sed_string
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: Generates a wrapped sed string, with a given number of
#LL           elements per line, suitable for parsing in a Makefile.
#LL
#LL  Inputs : $1 = a marker to create a sed string
#LL                e.g. @objects@. The marker will be replaced at a
#LL                later time with actual content
#LL           $2 = the number of elements per line
#LL           $3 = a list of space separated strings
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: qsconf, qsmncompile
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables:
#L    alltheobjs    : a list of space separated strings
#L    bigstring     : holds the result of gen_sed_string a wrapped sed
#L                    string with a given number of elements per line
#L    line_elements : the number of elements per line
#L    prefstr       : the sed prefix used to compose the resulting sed
#L                    string ($1 and other sed directives)
#L    smallstring   : used to hold each line of the wrapped string,
#L                    while it is being composed, prior to adding it to
#L                    bigstring
#L    suffstr       : the sed suffix used to compose the resulting sed
#L                    string
#L
#L   End of header -----------------------------------------------------

gen_sed_string()
{
  line_elements=$2
  prefstr="s^$1^"
  suffstr="^g"

  alltheobjs=$3

  (( counter = line_elements - 1 )) # Initialise counter
  bigstring=$prefstr                # Initialise bigstring

  for thisobj in $alltheobjs        # loop over all string entities
  do
    (( counter = counter + 1 ))
    if [ "$counter" -eq $line_elements ]
    then
     # start a new line
     counter=0
     if [ ! -z "$smallstring" ]
     then
       # smallstring exists, and has the maximum number of elements,
       # add it to bigstring
       bigstring=$bigstring'\\\\\\\\\\\\\\n'$smallstring
     fi
     # start a new line, reinitialise smallstring to current loop
     # element
     smallstring="$thisobj"
    else
     # add current loop element to line being composed
     smallstring="$smallstring $thisobj"
    fi
  done

  if [ ! -z "$alltheobjs" ]
  then
    echo -e $bigstring'\\\\\\\\\\\\\\n'$smallstring$suffstr
  else
    echo -e $bigstring$suffstr
  fi
}
