#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  initxport
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: Initialises & exports filenames of input and output
#LL           dumps/fieldsfiles.
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: fieldop
#L
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables: none
#L
#L   End of header -----------------------------------------------------

initxport()
{
# Temporary file in which commands to initialise and export FILE1
# FILE2 (and FILE3) are written.
tmpfile=$TMPDIR/tmp$$
rm $tmpfile 2> /dev/null

files=$#
i=0

while [ $# -gt 0 ]
do

 i=`expr $i + 1`
# Insert commands for initialising and exporting input and output
# filenames into temporary file.
 FILE=$1
 echo -e "FILE$i=$1" >> $tmpfile
 echo -e "export FILE$i" >> $tmpfile

 if [ ! -f  $FILE ]            # Check input files exist.
 then

   if [ $i -ne $files ]
   then

     echo -e "$FILE does not exist"
     exit 1

   fi
 fi
 shift

done

# Execute temporary file/script.
chmod +x $tmpfile
. $tmpfile

}
