#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL  Function:  mkdirhier
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: Makes a directory hierarchy
#LL
#LL  Current Owner: Anette Van der Wal
#LL  Reviewer: ????               Date of review: ????
#LL
#LL  Tested under OS version: UNICOS <UNICOS version number>
#LL  UM version no: 4.5       Date of test:  <date of test>
#LL
#LL  History:
#LL   Model
#LL  version  Date        Modification history:
#LL   4.5     14/07/98    Original version (A Van der Wal).
#LL
#LL  Programming standard: UMDP 3, version <UMDP 3 version number>
#LL
#LL  External documentation:
#LL    <UMDP number & name of external documentation>
#LL
#L   Interface and arguments: none
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: qsconf
#L   Calls    : none
#L
#L   Imports  : none
#L
#L   Exports  : none
#L
#L   Local variables: none
#L
#L   End of header -----------------------------------------------------

mkdirhier()
{
  if [ ! -d "$1" ]
  then
    mkdir -p $1 2> /dev/null
    if [ ! -d "$1" ]
    then
      echo -e "ERROR: cannot create directory \"$1\""
      exit 1
    fi
  else
    if [ ! -w $1 ] || [ ! -d $1 ]
    then
      echo -e "ERROR: cannot write to directory \"$1\""
      exit 1
    fi
  fi
}
