#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL-------------------------------------------------------------------
#LL  Script:  comp_parse
#LL-------------------------------------------------------------------
#LL
#LL  Purpose:	
#LL
#LL  Author:
#LL  Reviewer:
#LL
#LL  Tested under OS version:
#LL
#LL  Code version no: 4.3         Date:
#LL
#LL  Modification History:
#LL  vn4.3
#LL  vn4.3	17/03/97   Restructured original code.
#LL
#LL                        Added an if test on BUILDHOST to allow
#LL                        platforms other than the T3E or Cray vector
#LL                        parallel machines, to bypass comp_parse.
#LL                        This is an intermediate measure to allow
#LL                        testing to begin on other platforms.
#LL
#LL                        Added formal script header and comments.
#LL                        (S Robertson)
#LL  Programming standard:
#LL
#LL  Logical components covered: J00
#LL
#LL  External documentation:
#LL
#L   Interface and arguments: --------------------------------------
#L   BUILDHOST	- identifies the system the UM is being built upon
#L                e.g. CrPVPf77 machine and compiler
#L   COMPILER   - is the name of the compiler e.g. f90 or cf77
#L   BUILDTYPE	- describes the nature of a build; n(ormal), d(ebug)
#L                etc for the T3E
#L   ---------------------------------------------------------------
#L   Called by:	qsconf
#L   Calls:
#L
#L   Local variables:
#L   XCOMOPTS	- holds extra compiler options required for
#L                the type of build being done.

# set up environment variable as lowercase
typeset -l BUILDTYPE

BUILDHOST=$1
COMPILER=$2	
BUILDTYPE=$3

# set up local variables
XCOMOPTS=""

#echo -e $COMPILER $BUILDTYPE $BUILDHOST
# parse compiler options for given BUILDHOSTs
if [ $BUILDHOST = 'T3E_f90' ]
then

  # fortran f90 compiler options
  if [ $COMPILER = 'f90' ]
  then
    if [ $BUILDTYPE = 'n' ] || [ $BUILDTYPE = 'normal' ]
    then
      # normal build, default case no action required
      :
    elif [ $BUILDTYPE = 'd' ] || [ $BUILDTYPE = 'debug' ]
    then
      # debug compiler options
      XCOMOPTS=-g
    elif [ $BUILDTYPE = 'a' ] || [ $BUILDTYPE = 'apprentice' ]
    then
      # apprentice
      XCOMOPTS=-eA
    else
      # unknown build type; flag as an error an exit from the script
echo -e "ERROR: comp_parse : $BUILDTYPE is unknown build type." >&2
      exit 1
    fi

  # C compiler options
  elif [ $COMPILER = 'cc' ]
  then
    if [ $BUILDTYPE = 'n' ] || [ $BUILDTYPE = 'normal' ]
    then
      # normal build, default case is do nothing
      :
    elif [ $BUILDTYPE = 'd' ] || [ $BUILDTYPE = 'debug' ]
    then
      # debug compiler options
      XCOMOPTS=-g
    elif [ $BUILDTYPE = 'a' ] || [ $BUILDTYPE = 'apprentice' ]
    then
      # to enable the MPP apprentice tool
      XCOMOPTS=-happrentice
    else
      # unknown build type; flag as an error an exit from the script
      echo -e \
"ERROR: comp_parse : $BUILDTYPE is unknown build type." >&2
      exit 1
    fi
  else
    # unknown compiler; flag as an error an exit from the script
    echo -e \
"ERROR: comp_parse : $COMPILER is unknown compiler for $BUILDHOST" >&2
    exit 1
  fi

elif [ $BUILDHOST = 'CrPVPf77' ]
then
  # fortran 77 compiler options
  if [ $COMPILER = 'cf77' ]
  then
    if [ $BUILDTYPE = 'n' ] || [ $BUILDTYPE = 'normal' ]
    then
      # normal build, default case no action required
      :
    elif [ $BUILDTYPE = 'd' ] || [ $BUILDTYPE = 'debug' ]
    then
      # debug compiler options
      XCOMOPTS=-g
    else
      # unknown build type; flag as an error an exit from the script
      echo -e \
"ERROR: comp_parse : $BUILDTYPE is unknown build type." >&2
      exit 1
    fi
  else
    # unknown compiler; flag as an error an exit from the script
    echo -e \
"ERROR: comp_parse : $COMPILER is unknown compiler for $BUILDHOST." >&2
    exit 1
  fi

else # marker : put code for other BUILDHOSTs here
  # unknown buildhost; flag as an error an exit from the script
  echo -e \
"WARNING: comp_parse : the system $BUILDHOST is unknown : DO NOTHING" \
  >&2
fi

# return contents of XCOMOPTS
echo -e $XCOMOPTS



