#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
# Script to parse the loader line
#
# input variables:
#    LCOM_CMD          Name of loader being used
#    load vars         defined in central compile file for this
#                      compiler/loader
#                      eg. CLD_LIBS, CLD_OPTS, CLD_PATH, CLD_FILE
#                          for T3E cld loader
#    APPRENTICE        set to true if apprentice options used anywhere
#
# output variables:
#    LCOM_OPTS         Complete line of options to pass into compiler
#                      for the current deck and build options

APPRENTICE="false"


  if test $LCOM_CMD = 'cld'
  then

    # for each variable type get value this time round
    # if value is passed in via env var no need to do this


    # If this is part of a build include OBJXREF compiler commands
    # The build types here must correspond to those at the top of
    # the obj_xref file for this machine/compiler type.

    if $APPRENTICE
    then

      CLD_LIBS="$CLD_LIBS -lapp"

    fi    # $APPRENTICE


    # Make empty environment variables usable
    # and add in extra options where necessary.

    if test -z "$CLD_LIBS"
    then
      CLD_LIBS=""
    else
      CLD_LIBS="-l $CLD_LIBS"
    fi

    if test -z "$CLD_PATH"
    then
      CLD_PATH=""
    else
      CLD_PATH="-L $CLD_PATH"
    fi

    if test -z "$CLD_FILE"
    then
      CLD_FILE=""
    else
      CLD_FILE="-f $CLD_FILE"   # check option - may not be necessary
    fi


    # substitute into command line:

    LCOM_OPTS="$CLD_LIBS $CLD_PATH $CLD_OPTS"
    export LCOM_OPTS
    echo -e LCOM_OPTS are "$LCOM_OPTS"

  else

    echo -e 'Error: unknown loader'

  fi # cld
