#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
########################################################################
#LL Unified Model combine Script
#LL Author: A.Sangster
#LL Date: 12 January
#LL Purpose: combine control and history files, giving interim history
#LL Arguments: $1 - History file (input)
#LL            $2 - Interim control file (input)
#LL            $3 - Operational houskeeping file (input)
#LL            $4 - Interim history file (output)
#LL            $5 - FORTRAN unit assignment file (output)
#LL Called by: UM prelim script
#LL Calls    : none
#LL   Imports:
#LL     SETOPT   -set shell options
#LL     OUTPUT   -printed output file pathname
#LL   Exports:
#LL     UNIT01   -house keepring file
#LL     UNIT09   -interim control (preliminary job only)
#LL     UNIT10   -permanent history file pathname
#LL     UNIT11   -interim history file pathname
#LL     UNIT13   -machineable version of external file table
#LL   Local variables:
#LL     CC       -script/executable completion code
#LL Modification history:
#LL 10/01/92 R A Stratton : Replaced TMPDIR by TEMP.
#LL  8/02/93 C S Douglas  : Environment variable FILENV removed, assign
#LL          statements replaced with UNIT environment variables for
#LL          FORTRAN I/O portability.
#LL C D Perks 17/12/93 - Included details of imports,exports,
#LL                      and local variables.
#LL 16/05/95 C D Perks - Removed unit 1 and 9 (housekeeping and interim)
#LL                      and placed these in qspickup and qssetup.  I
#LL 17/02/96 L C Wiles - Added assign statements for namelist reads.
#LL
#L----------------------------------------------------------------------
#L
#L Step 0 - Setup environment variables
#L
set -$SETOPT
#L
#L Step 1  - Execute load module, appending standard output to OUTPUT
#L
UNIT10=$1
UNIT11=$2
UNIT13=$3
export UNIT10 UNIT11 UNIT13
#
#
qxcombine >>$OUTPUT
#
CC=$?
if test $CC -ne 0
then
  echo -e "$0: Job failed"
  exit 135
else
  echo -e "$0: Job terminated normally"
fi
