#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL
#LL Unified Model histreset Script
#LL Author: A.Sangster
#LL Date: 15 January
#LL
#LL Purpose: Ensure only have current and previous history records in
#LL          permanent history file ( Operational runs only )
#LL
#LL Arguments: $1 - Permanent History file (input/output)
#LL
#LL Called by: UM final script
#LL Calls    : none
#LL   Imports:
#LL     SETOPT        -set shell options
#LL     QXHISTRESET   -execute load module
#LL   Exports:
#LL     UNIT10        -permanent history file pathname
#LL   Local variables:
#LL     CC            -script/executable completion code
#LL
#LL Modification history:
#LL 10/01/92 R A Stratton : Replaced references to TMPDIR by TEMP
#LL  8/02/93 C S Douglas  : Environment variable FILENV removed, assign
#LL          statements replaced with UNIT environment variables for
#LL          FORTRAN I/O portability.
#LL C D Perks 17/12/93 - Included details of imports,exports,
#LL                      and local variables.
#L ---------------------------------------------------------------------
#L
#L Step 0 - Setup environment variables
#L
set -$SETOPT
#L
#L Step 1  - Execute load module, appending standard output to OUTPUT
#L
UNIT10=$1
export UNIT10
#
qxhistreset >>$OUTPUT
#
CC=$?
if test $CC -ne 0
then
  echo -e "$0: Job failed"
  exit 135
else
  echo -e "$0: Job terminated normally"
fi
