#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL
#LL Unified Model histprint Script
#LL Author: A.Sangster
#LL Date: 20 March 1990
#LL
#LL Purpose: To print out the contents of history file records
#LL
#LL
#LL Arguments: $1 - History file  (input)
#LL            $2 - Resubmit file (output)
#LL
#LL Called by: UM final script
#LL Calls    : none
#LL Modification history:
#LL
#LL 10/01/92 R A Stratton : Replaced references to TMPDIR by TEMP
#LL  8/02/93 C S Douglas  : Environment variable FILENV removed, assign
#LL          statements replaced with UNIT environment variables for
#LL          FORTRAN I/O portability.
#LL C D Perks 17/12/93 - Included details of imports,exports,
#LL                      and local variables.
#LL  Imports:
#LL    OUTPUT          -printed output file pathname
#LL    HISTNLIST       -history file namelist
#LL    QXHISTREPORT    -executable load module
#LL  Exports:
#LL    UNIT10          -permanent history file pathname
#LL    UNIT07          -error output for operators-operational model
#LL  Local variables:
#LL    CC              -script/executable completion code
#LL
#L --------------------------------------------------------------------
#L
#L Step 0 - Setup environment variables
#L
#L
#L Step 1  - Execute load module, appending standard output to OUTPUT
#L           and reading user supplied namelist data on standard input
#L
UNIT10=$1
UNIT07=$2
export UNIT10 UNIT07
#
qxhistreport <$HISTNLIST >>$OUTPUT
#
CC=$?
if test $CC -ne 0
then
  echo -e "$0: Job failed"
  exit 135
else
  echo -e "$0: Job terminated normally"
fi
