#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
#LL---------------------------------------------------------------------
#LL  Script:  qspickup
#LL---------------------------------------------------------------------
#LL
#LL  Purpose: Append temporary or interim history record to end of
#LL           permanent history file after model run completes.
#LL
#LL  Author:   A B Sangster       Date:           11 May 1990
#LL  Reviewer: M A Smith          Date of review:
#LL
#LL  Tested under OS version: UNICOS 5.1.10
#LL
#LL  Code version no: 2.0         Date: 15 July 1991
#LL
#LL  Modification History:
#LL    16/07/91 - qspickup renamed from qserror_pickup as new script
#LL      handles normal as well as error post-processing.  (TCJ)
#LL      In-line documentation also improved.
#LL     8/02/93 - FILENV environment variable removed, assign statements
#LL      replaced with UNIT environment variables for FORTRAN I/O
#LL      portability.
#LL  3.5  16/05/95 - introduced UNIT09 for copy of old history file
#LL  4.4  28/05/97 - assign satements for namelist reads on t3e
#LL                  protected by *DEF CRAYF90 for portability. LCW
#LL
#LL  Programming standard: UM Doc Paper 3A, version 1 (29/10/90)
#LL
#LL  Project task: C0
#LL
#LL  Logical components covered: J031
#LL
#LL  External documentation:
#LL    UM Doc Paper C0 - The top-level control system
#LL
#L   Interface and arguments: ------------------------------------------
#L
#L   qspickup from_hist perm_hist_file
#L
#L     {from_hist} ::= interim history file to update from (input)
#L     {perm_hist_file} ::= permanent history file (input/output)
#L
#L   -------------------------------------------------------------------
#L
#L   Called by: qsprelim script
#L              qsfinal script
#L   Calls    : qxpickup executable
#L
#L   Imports:
#L     SETOPT        - Shell options
#L     TEMP          - Temporary directory name
#L     OUTPUT        - Formatted output file
#L
#L   Exports:
#L     UNIT09
#L     UNIT12        - FORTRAN unit environment
#L     UNIT10
#L
#L   Local variables:
#L     CC            - Completion code
#L
#L----------------------------------------------------------------------
#L Step 0 - Set up environment variables
#L
set -$SETOPT
#L----------------------------------------------------------------------
#L Step 1 - Execute load module, appending standard output to OUTPUT
#L
UNIT09=$TEMP/$RUNID.chist
UNIT12=$1
UNIT10=$2
if test -f $UNIT10
then
  cp $UNIT10 $UNIT09
fi
export UNIT09 UNIT12 UNIT10
#

qxpickup >>$OUTPUT
#
CC=$?
if test $CC -ne 0
then
  echo -e "$0: Failure in qxpickup"
  exit 135
else
  echo -e "$0: Normal completion"
fi
