#!/bin/ksh
# ----------------------------- COPYRIGHT ---------------------------- #
#           (c) BRITISH CROWN COPYRIGHT 2000, THE MET.OFFICE           #
#                                                                      #
# Use, duplication or disclosure of this code is subject to the        #
# restrictions as set forth in the contract. If no contract has been   #
# raised with this copy of the code, use, duplication or disclosure    #
# of it is strictly prohibited. Permission to do so must be obtained   #
# in writing from the Head of Numerical Modelling at The Met. Office.  #
# ----------------------------- COPYRIGHT ---------------------------- #
########################################################################
#LL Unified Model Setup Script
#LL Author: A.Sangster
#LL Date: 11 January
#LL Purpose: Sets up interim control file and FORTRAN unit assignment
#LL          file from master control and houskeeping file ( if
#LL        operational)
#LL Arguments: $1 - Master control file
#LL            $2 - Interim history file
#LL            $3 - FORTRAN unit assignment file
#LL Called by: UM prelim script
#LL Calls    : none
#LL   Imports:
#LL     SETOPT   -set shell options
#LL   Exports:
#LL     UNIT01   -house keeping file
#LL     UNIT08   -pipe pathname for communication with qsserver
#LL     UNIT11   -interim history file pathname
#LL     UNIT13   -machineable version of external file table
#LL   Local variables:
#LL     CC       -script/executable completion code
#LL Modification history:
#LL 10/01/92 R A Stratton : Replaced TMPDIR by TEMP
#LL  8/02/93 C S Douglas  : Environment variable FILENV removed, assign
#LL          statements replaced with UNIT environment variables for
#LL          FORTRAN I/O portability.
#LL C D Perks 17/12/93 Included details of imports,exports,
#LL                    and l*ocal variables.
#LL 16/05/95 C D Perks Removed UNIT01=housekeeping file (now in qsmain)
#LL 17/02/97 L C Wiles Add assign statements for namelist IO
#L --------------------------------------------------------------------
#L
#L Step 0 - Setup environment variables
#L
set -$SETOPT
#L
#L Step 1  - Execute load module, appending standard output to OUTPUT
#L
UNIT08=$1
UNIT11=$2
UNIT13=$3
export UNIT08 UNIT11 UNIT13
#
#
qxsetup >>$OUTPUT
#
CC=$?
if test $CC -ne 0
then
  echo -e "$0: Job failed"
  exit 135
else
  echo -e "$0: Job terminated normally"
fi
